/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "funixgaming-spring-core"

include(":crud")
include(":exceptions")
include(":tools")
include(":storage")
include(":test-utils")
