/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(project(":exceptions"))
    api(libs.org.springframework.spring.websocket)
    api(libs.org.apache.pdfbox.pdfbox)
}

group = "dev.funixgaming.spring.core.tools"
description = "tools"

java {
    withJavadocJar()
}
