# This is a basic workflow to help you get started with Actions

name: Push Maven package to FunixProductions repository

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish-funixproductions-mvn-package:
    name: Publish to FunixProductions Maven Package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven settings
        run: |
          mkdir -p $HOME/.m2
          cp .github/settings.xml $HOME/.m2/settings.xml

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode clean deploy -T 6
        env:
          MAVEN_USERNAME: ${{ secrets.FUNIXPROD_MVN_REPO_USER }}
          MAVEN_PASSWORD: ${{ secrets.FUNIXPROD_MVN_REPO_TOKEN }}
          ENCRYPTION_KEY: hwJdNY1/yC3miXQR+Vw2V3qtt1e3FPJ2y62BKtROUJs=
          ENCRYPTION_IV: DKKyySzj8ao5WgraQpwj+A==
