# This is a basic workflow to help you get started with Actions

name: Push Maven package to github repository

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode clean deploy -T 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENCRYPTION_KEY: hwJdNY1/yC3miXQR+Vw2V3qtt1e3FPJ2y62BKtROUJs=
          ENCRYPTION_IV: DKKyySzj8ao5WgraQpwj+A==
